<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/PendingApprovals_REQUEST/types" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/REST/PendingApprovals_REQUEST" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/PostMessage_REQUEST" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns2="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/PostMessage" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/PostMessage_REQUEST/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ns1 oraext xsd xp20 ora oracle-xsl-mapper xsi fn xsl ignore01 ns33 ns30 ns34 ns31 ns35" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/GetApprovals_REQUEST/types" xmlns:nsmpr2="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:ns23="http://xmlns.oracle.com/cloud/adapter/connectivityproperties/REST/GetApprovals_REQUEST/RESTOUTREQ" xmlns:ns22="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/GetApprovals" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns24="http://xmlns.oracle.com/cloud/adapter/REST/PostMessage/types" xmlns:orajs0="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath86288" xmlns:ns3="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.resources.icsxpathfunctions.ICSInstanceTrackingFunctions" xmlns:ns21="http://xmlns.oracle.com/cloud/adapter/REST/GetApprovals_REQUEST" xmlns:ns0="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns25="http://xmlns.oracle.com/cloud/adapter/connectivityproperties/REST/PostMessage_REQUEST/RESTOUTREQ" xmlns:ns19="http://xmlns.oracle.com/cloud/adapter/REST/GetApprovals/types" xmlns:ns33="http://xmlns.oracle.com/procmon" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns30="http://xmlns.oracle.com/cloud/adapter/REST/PendingApprovals_REQUEST/request/types" xmlns:ns34="http://xmlns.oracle.com/ics/tracking/ics_tracking_context.xsd" xmlns:ns31="http://xml.oracle.com/adapters/extension" xmlns:ns35="http://xmlns.oracle.com/cloud/adapter/REST/GetApprovals_REQUEST/request/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_18/outbound_19/resourcegroup_20/PendingApprovals_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/PendingApprovals_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_42">
            <oracle-xsl-mapper:schema location="../../application_30/inbound_31/resourcegroup_32/GetApprovals_REQUEST.wsdl" xml:id="id_43"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/GetApprovals_REQUEST/types" xml:id="id_44"/>
            <oracle-xsl-mapper:param name="GetApprovals" xml:id="id_45"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_68">
            <oracle-xsl-mapper:schema location="../../processor_77/resourcegroup_78/ICSIntegrationMetadata.xsd" xml:id="id_69"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_70"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_71"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_47/inbound_48/resourcegroup_49/PostMessage_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/PostMessage_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="GetApprovals" xml:id="id_54"/>
   <xsl:param name="self" xml:id="id_73"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <ns24:request-wrapper xml:id="id_31">
            <ns24:blocks xml:id="id_34">
               <ns24:text xml:id="id_35">
                  <ns24:text xml:id="id_38">
                     <xsl:value-of xml:id="id_39" select="concat (&quot;Flexdeploy has &quot;, concat (count ($GetApprovals/nsmpr1:executeResponse/ns19:response-wrapper/ns19:topLevelArray ), &quot; pending approvals&quot; ) )"/>
                  </ns24:text>
                  <ns24:type xml:id="id_36">
                     <xsl:value-of xml:id="id_37" select="&quot;mrkdwn&quot;"/>
                  </ns24:type>
               </ns24:text>
               <ns24:type xml:id="id_40">
                  <xsl:value-of xml:id="id_41" select="&quot;section&quot;"/>
               </ns24:type>
            </ns24:blocks>
            <ns24:channel xml:id="id_32">
               <xsl:value-of xml:id="id_33" select="dvm:lookupValue (&quot;tenant/resources/dvms/SlackChannels&quot;, &quot;Instance&quot;, $self/nsmpr2:metadata/nsmpr2:environment/nsmpr2:serviceInstanceName, &quot;Channel&quot;, &quot;flexdeploy-test&quot; )"/>
            </ns24:channel>
         </ns24:request-wrapper>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>
